---

transcriptome: "http://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz"

annotation: "http://ftp.ensembl.org/pub/release-95/gtf/homo_sapiens/Homo_sapiens.GRCh38.95.gtf.gz"

Samples:
    - "Condition.1":   # this is a group 
        A1: "RawData/condition1_rep1.fastq.gz"    # filename pairs must be maintained - identifier and filename
        A2: "RawData/condition1_rep2.fastq.gz"
        A3: "RawData/condition1_rep3.fastq.gz"

    - "Condition.2":  # this is another group - names are arbitrary but must be unique
        B1: "RawData/condition2_rep1.fastq.gz"
        B2: "RawData/condition2_rep2.fastq.gz"
        B3: "RawData/condition2_rep3.fastq.gz"

referenceGroup: "Condition.1"   # this name *must* match one of the group names  

minimap_index_opts: ""

minimap2_opts: ""

maximum_secondary: 100

secondary_score_ratio: 1.0

salmon_libtype: "SF"

# Count filtering options - customize these according to your experimental design:

# Genes expressed in minimum this many samples:
min_samps_gene_expr: 3
# Transcripts expressed in minimum this many samples:
min_samps_feature_expr: 1
# Minimum gene counts:
min_gene_expr: 10
# Minimum transcript counts:
min_feature_expr: 3


lfcThreshold : 1            # minimum required log2 fold change for differential expression analysis
adjPValueThreshold: 0.05    # adjusted p-value threshold for differential expression analysis


threads: 50
tutorialText: TRUE


