channels:
  - bioconda
  - conda-forge
  - sagrudd
  - r
dependencies:
  - snakemake
  - python
  - r
  - rstudio
  - pandas
  - salmon
  - minimap2
  - samtools==1.1.0
  - graphviz
  - imagemagick
  - bioconductor-drimseq
  - bioconductor-annotationdbi
  - bioconductor-genomicfeatures
  - bioconductor-dexseq
  - bioconductor-stager
  - bioconductor-shortread
  - r-devtools
  - r-session
  - r-writexl
  - r-kableextra
